//go:build tinygo.wasm

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.21.9
// source: test.proto

package plugin

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
)

const DataPasserPluginAPIVersion = 1

//export data_passer_api_version
func _data_passer_api_version() uint64 {
	return DataPasserPluginAPIVersion
}

var dataPasser DataPasser

func RegisterDataPasser(p DataPasser) {
	dataPasser = p
}

//export data_passer_pass_data
func _data_passer_pass_data(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	var req PassDataRequest
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := dataPasser.PassData(context.Background(), req)
	if err != nil {
		return 0
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//export data_passer_pass_data_error
func _data_passer_pass_data_error(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	var req PassDataRequest
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := dataPasser.PassDataError(context.Background(), req)
	if err != nil {
		return 0
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}
